/*
OOP is programming paradigm which means thatit is a set of rules and ideas and
concepts it is basically a standard in programmingthat we use to solve a specific type of problem
 */


/*
the idea behind object-oriented paradigm is we want to be able to represent real-life objects,
real-life entities together with their characteristics, with their ,attributes and their behaviors we want
to be able to explain
those objects to our computer and to
represent those objects
in our program and that is exactly what
oop
*/


/*
a class is basically user
user-defined
data type and in order to be able to
understand what are user-defined data
types
you first need to understand what are
pre-defined data types what are built-in
data types so
data types like integer and float and
double and character
and so on
*/

/*
access modifiers

private:
private means that whatever is private
in your class
that is not going to be accessible
outside of your class that is basically
going to be hidden

public:
public means that
whatever is public in your class
you will be able to access that outside
of your class as well so anyone else
outside of your class is going to be
able to access
public members of your class

protected:
protect it is somewhere in between private and
public and it has certain rules.

*/



/*
constructor
 */
/*
class Car {
  name ;
  color ;
  hasGps;
}
const car1 = new Car();
car1.name = 'Ford';
car1.color = 'red';
car1.hasGps = true;

const car2 = new Car();
car2.name = 'Kia';
car2.color = 'white';
car2.hasGps = true;
console.log("🚀 ~ car1", car1)
console.log("🚀 ~ car2", car2)
*/

/*
constructor
is a special type of method that is
invoked
each time that an object of a class
is created so whenever you create an
object
of a class a constructor is invoked
*/

/*
what is default constructor?
default constructor is a term
to describe a constructor that is
automatically generated by your compiler
so
in case that you don't create a
constructor of your own
your compiler is going to automatically
give you a
constructor which is called default
constructor
*/

/*
class Car {
  constructor(name,color,hasGps){
    this.name = name;
    this.color = color;
    this.hasGps = hasGps;
  }

}
const car1 = new Car('Ford','red',true);

const car2 = new Car('Kia','white',true);

console.log("🚀 ~ car1", car1)
console.log("🚀 ~ car2", car2)
*/